branch-defaults:
  master:
    environment: development
environment-defaults:
  development:
    branch: null
    repository: null
global:
  application_name: mont-experiences-ui
  default_ec2_keyname: mont public
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.4.5
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
